### ISSUE TITLE
GloBI unable to read Coccidae of Egypt

### ISSUE THREAD

**Issue by jhpoelen** [millerse/Coccidae-of-Egypt#1]
According to http://www.globalbioticinteractions.org/status.html (see screenshot below), GloBI was unable to read interactions published in this repository. Suggest to work with @jhammock to enable the travis integration. Also see http://github.com/jhpoelen/eol-globi-data/wiki/Dataset-Management .

![coccidae](https://cloud.githubusercontent.com/assets/1084872/22116604/d85985e8-de25-11e6-9fec-bfa6b7cb7737.png)

**Comment by millerse** [comment]
Turns out the interaction name and ID were switched.  Fixed

**Comment by jhpoelen** [comment]
@millerse thanks for fixing this! your changes should propagate in a day or two.

**Comment by jhpoelen** [comment]
btw  - @millerse @jhammock did you consider using the readability check to get pretty immediate feedback on whether the issue has been resolved? See https://github.com/jhpoelen/eol-globi-data/wiki/Dataset-Management#readability for more info.
